# SPDX-FileCopyrightText: 2026 Kiloloop
# SPDX-License-Identifier: Apache-2.0

"""Drift guard: the README command table must match ``oacp --help``.

The table is generated by ``scripts/gen_readme_commands.py`` (``make docs``);
these tests fail when README.md falls behind the CLI help text, when the help
text falls behind the dispatcher, or when the generator's check mode stops
reporting drift.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))
sys.path.insert(0, str(REPO_ROOT))

from gen_readme_commands import (  # noqa: E402
    BEGIN_MARKER,
    END_MARKER,
    README_PATH,
    extract_block,
    load_help_text,
    main,
    parse_commands,
    render_block,
)
from oacp.cli import DELEGATED_COMMANDS, SCRIPT_NAMES  # noqa: E402


def _readme_text() -> str:
    return README_PATH.read_text(encoding="utf-8")


def test_readme_command_table_matches_help_text() -> None:
    expected = render_block(parse_commands(load_help_text()))
    actual = extract_block(_readme_text())
    assert actual == expected, (
        "README.md command table is behind oacp --help; run `make docs`"
    )


def test_help_text_matches_executed_cli_help() -> None:
    # The executed comparison: what `oacp --help` actually prints from this
    # checkout, not the constant alone.
    proc = subprocess.run(
        [sys.executable, "-m", "oacp.cli", "--help"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    assert parse_commands(proc.stdout) == parse_commands(load_help_text())


def test_help_text_lists_exactly_the_dispatchable_commands() -> None:
    names = [name for name, _ in parse_commands(load_help_text())]
    assert len(names) == len(set(names)), f"duplicate command in HELP_TEXT: {names}"
    assert sorted(names) == sorted([*SCRIPT_NAMES, *DELEGATED_COMMANDS])


def test_parse_commands_rejects_help_text_without_commands_block() -> None:
    with pytest.raises(ValueError):
        parse_commands("Usage: oacp <command>\n\nExamples:\n  oacp doctor\n")


def test_check_mode_reports_drift_and_write_mode_repairs_it(tmp_path: Path) -> None:
    expected = render_block(parse_commands(load_help_text()))
    stale_rows = "\n".join(expected.splitlines()[1:5])  # header + first two rows
    stale_block = "\n".join([BEGIN_MARKER, stale_rows, END_MARKER])
    readme = tmp_path / "README.md"
    readme.write_text(
        _readme_text().replace(extract_block(_readme_text()), stale_block, 1),
        encoding="utf-8",
    )

    assert main(["--check", "--readme", str(readme)]) == 1
    assert main(["--write", "--readme", str(readme)]) == 0
    assert extract_block(readme.read_text(encoding="utf-8")) == expected
    assert main(["--check", "--readme", str(readme)]) == 0
